# Site settings
title: Anand Vemparala's CV 
description: Anand's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: V Anand Shankar
  title: Data Scientist
  address: Vancouver, British Columbia
  email: vanandshankar@yahoo.com
  link: https://github.com/vanandsh/vanandsh2.github.io.git
  weibo:
  github: vanandsh
  linkedin: 
  twitter: 
  gavatar: /vanandsh2.github.io/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Intel
      location: Bangalore, India
      title: Software Developement Engineer
      started: 2014
      duration: (2014 - Present)
      description: Informatica MDM and IDQ Developer
  educationHistory:
    - education1:
      organization: University of British Columbia
      location: Vancouver, British Columbia
      degree: Masters
      major: Data Science
      started: 2019
      duration: (2019 - 2020)
      description: Pursuing Masters in Data Science
  languages:
    - language1:
      name: Hindi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
